apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-integer
  namespace: dataops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-integer
  template:
    metadata:
      labels:
        app: random-integer
    spec:
      containers:
      - name: random-integer
        image: datapains/prometheus-example-app:0.0.1
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
