apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataops-app
  namespace: dataops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataops
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: dataops-app
        image: datapains/prometheus-example-app:0.0.1
        imagePullPolicy: Never
        ports:
        - name: metrics
          containerPort: 8000
