apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataops-app
  namespace: dataops-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dataops
  template:
    metadata:
      labels:
        app: dataops
    spec:
      containers:
      - name: dataops-app
        image: quay.io/brancz/prometheus-example-app:v0.5.0
        ports:
        - name: web
          containerPort: 8080
