apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataops-app
  namespace: dataops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataops
  template:
    metadata:
      labels:
        app: dataops
    spec:
      containers:
      - name: dataops-app
        image: 
        ports:
        - name: metrics
          containerPort: 8000
