kind: Service
apiVersion: v1
metadata:
  name: random-integer
  namespace: monitoring
  labels:
    app: random-integer
spec:
  selector:
    app: random-integer
  ports:
    - name: metrics
      port: 9102
      targetPort: 8000
      protocol: TCP
