apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dataops-app
  namespace: dataops
  labels:
    team: dataops
spec:
  selector:
    matchLabels:
      app: dataops
  endpoints:
  - port: 8000
    interval: 10s
