apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: random-integer-servicemonitor
  namespace: dataops
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: random-integer
  endpoints:
    - port: metrics
      interval: 10s
