apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: dataops
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
